### ISSUE TITLE
Bug: Listing Extension Store Settings

### ISSUE THREAD

**Issue by medihaaziz** [clay/clay-kiln#1001]
## Bug
1) Go to cut and create a weddings listing 
2) scroll down to shop extension
3) click product&services tab
4) click add item

Note that the open window mixes into the background. Here is a reference link: 
http://www.thecut.com/pages/cja04kriv00dlbfyenvvvkstn.html?edit=true#listing-extension-store~cja04krj000dqbfyev92llvy9~settings

**Comment by nelsonpecora** [comment]
Can you please add a screenshot of this issue? I'm not sure what's going on.

**Comment by pfeytser** [comment]
This is happening because the form height is being adjusted when items are added to a complex-list, and that complex-list contains `_reveal` fields, which are interacting with the height calculation in a weird way.

**Comment by nelsonpecora** [comment]
should be fixed in commit 83ef0e3

**Comment by pfeytser** [comment]
QA Acceptance Criteria

- The bug logged about weddings above has been resolved.

**Comment by medihaaziz** [comment]
@pfeytser and @nelsonpecora I am still seeing the issue on production.

**Comment by nelsonpecora** [comment]
@medihaaziz correct, kiln 5.1.0 hasn't been added to sites or released on prod https://github.com/nymag/sites/pull/4174

**Comment by medihaaziz** [comment]
@nelsonpecora can you scratch the cut to kiln-510 so I can test this?

**Comment by nelsonpecora** [comment]
@medihaaziz added the cut: http://kiln-510.thecut.sites.aws.nymetro.com/pages/homepage.html
